### ISSUE TITLE
About IntegerAsn1 methods and RSAPublicKey

### ISSUE THREAD

**Issue by hug-dev** [Devolutions/picky-rs#12]
Hi 😃 

When using `IntegerAsn1`, there are methods available to convert it to signed or unsigned bytes slices (`as_signed_bytes_be` and `as_bytes_be`) and create one from signed vector (`from_signed_bytes_be`).

Would it make sense to also be able to create one from a positive unsigned vector of bytes? Currently the following as to be done by hand, to create a valid positive ASN.1 integer from unsigned `bytes`:

```rust
// bytes is a Vec<u8>, representing a positive integer
if bytes[0] & 0x80 == 0x80 {
    bytes.insert(0, 0x00);
}
let bytes = IntegerAsn1::from_signed_bytes_be(bytes);
```

A method named `from_positive_bytes_be` (or similar) could maybe do that?

Also, would it make sense to create a ASN.1 `RSAPublicKey` implementation structure?
```
RSAPublicKey ::= SEQUENCE {
    modulus           INTEGER,  -- n
    publicExponent    INTEGER   -- e
}
```

**Comment by bcortier-devolutions** [comment]
Hi!
You're right, maybe we should add this :slightly_smiling_face: 

I think I didn't add it initially because operation is more complex than `from_signed_bytes_be` (only moving the vector).
By inserting at the beginning of the vector what is happening is a full copy of all elements to the right. See https://doc.rust-lang.org/src/alloc/vec.rs.html#993-1016
I figured it would be better to let the user build a valid signed vector of bytes by himself maybe faster than what I could do from a Vec inside a `from_signed_bytes_be` method or a least knowing that the insert operation has high cost.
But as pointed out most users are probably just expecting this method to exist even if it's not performant.

Also, I was thinking about renaming `as_bytes_be` to `as_unsigned_bytes_be` to be more explicit about what is happening. Is that your opinion too?

**Comment by hug-dev** [comment]
Good point about performance 👌
I do not see how to avoid the copy though once you have a `Vec<u8>` and you want to add `0x00` at the start 😕 I think letting the user know that this operation is `O(n)` in space and time is fair enough.

> Also, I was thinking about renaming as_bytes_be to as_unsigned_bytes_be to be more explicit about what is happening. What do you think?

It's a good suggestion! To be fair, when reading the implementation I had to look through the ASN.1 specs and Stack Overflow to understand what was up with that `0x00` in front, maybe a documentation comment explaining what is happening might help as well 😋

**Comment by bcortier-devolutions** [comment]
I publish picky-asn1-der 0.2, [here's the new method](https://docs.rs/picky-asn1/0.2.0/picky_asn1/wrapper/struct.IntegerAsn1.html#method.from_unsigned_bytes_be).  :slightly_smiling_face:

**Comment by bcortier-devolutions** [comment]
Oh, I forgot to answer to your second question. Actually we did implement RSAPublicKey in `picky` for our own usage: https://github.com/Devolutions/picky-rs/blob/master/picky/src/private/subject_public_key_info.rs
However, it's currently not in the public API because this isn't the purpose of `picky`. I'm not sure it would make sense to add RSAPublicKey directly in `picky-asn1` itself because this is a composed type.

**Comment by hug-dev** [comment]
Thanks for the release, it looks good and we are gonig to use that now!
Thanks for the info about RSAPublicKey! It was only coming from the fact that we are also creating this structure ourselves but we have to do it at two different locations, independently, and duplicating some code.
I am just thinking out loud but if those composed types are also ASN.1 standard, would it make sense to create a `picky-asn1-composed` (or something similar) crate 😃? 

PS: I do not want to be picky (pun intended) and it is not urgent at all but maybe it would be nice to add a check if `bytes` are empty in the new `from_unsigned_bytes_be` method so that it does not panic 😃 (Or should it?)

**Comment by bcortier-devolutions** [comment]
Okay I discussed with my team leader and we agreed to port some stable composed data types in a separate crate (would probably called `picky-asn1-x509`). The main reason for us to keep most of our X.509 composed types hidden is for stability concerns (definition support might be partial, or it might be a definition from a draft RFC, etc). However,`RSAPublicKey` is indeed a type quite stable and would be an ideal candidate. Not only `RSAPublicKey`, I think our PKCS#8 (no support for attributes though),  PKCS#10 and date related implementations might be good candidates too. We could also hide "unstables" types behind an "unstable" feature gate. 

Also you're right about the required check in `from_unsigned_bytes_be` haha (nice pun)! I'll add the check and release a minor patch :slightly_smiling_face: 

By the way, we welcome pull requests. Once we release our `picky-asn1-x509` crate, if you want to get merged some types I don't see any issue.

**Comment by hug-dev** [comment]
Excellent! Thanks for your support 😄 
We will definitely think about contributing in the future if we need to get some other types merged!

**Comment by hug-dev** [comment]
Hello!

I am coming back on this issue, as we might be about to also need the PKCS#1 type, `RSAPrivateKey` defined [here](https://tools.ietf.org/html/rfc8017.html).
Did you, by any chance, publish the `picky-asn1-x509` crate somewhere 😃? No worries if not! I think, as far as I know, `RSAPublicKey` and `RSAPrivateKey` are the only two types we need so it is not much work. We can define them ourselves, but as always, code re-use is more optimal.

**Comment by bcortier-devolutions** [comment]
Hi!

I didn't publish yet, but you're right we should do that now so that we can share common piece of code easily and all benefit from potential bug fixes and improvements! :slightly_smiling_face: 
For example, our version doesn't support `PrivateKeyInfo` attributes, because we don't have a use case for it yet, but we would welcome community contribution to centralize one good `PrivateKeyInfo` type definition. :+1: 
I'll move our currently private types in a new crate. Also, I'll have a look at other stuff generic enough to be moved there (for instance OIDs defined in https://github.com/Devolutions/picky-rs/blob/master/picky/src/oids.rs 
So you guys can add a dependency on `picky-asn1-x509` without pulling `picky`-specific additional dependencies.
I'll make some time today for this!

**Comment by bcortier-devolutions** [comment]
Almost there, but I need a little bit more of time to clean up stuff a little bit. You can find it in [picky-asn1-x509 branch](https://github.com/Devolutions/picky-rs/tree/picky-asn1-x509/picky-asn1-x509).
Crate itself is compiling and should be ready to use (code is the same as the one we use in production), but I need to change stuff in tests (currently not compiling) before publishing on crates.io. I'll finish that on Monday!

**Comment by hug-dev** [comment]
That's awesome, thanks 😄!! We will pull the dependency from GitHub directly until the crate is available 👌

**Comment by bcortier-devolutions** [comment]
It's now published! :smile: 
https://crates.io/crates/picky-asn1-x509

**Comment by hug-dev** [comment]
Great!! Thanks a lot 💯
