### ISSUE TITLE
origin on test data, and missing license files in published picky-test-data crate

### ISSUE THREAD

**Issue by decathorpe** [Devolutions/picky-rs#332]
This is a followup for https://github.com/Devolutions/picky-rs/issues/230 and https://github.com/Devolutions/picky-rs/pull/232 .

It looks like adding license files to the crate was missed when the test data was moved to a separately published crate.

Note that it's also not really clear what the source of the test data is. Are the keys / certificates / etc. just generated manually from /dev/random randomness source? Or are they from some other origin? The README does not say, and I'm wary of shipping binary blobs in the Fedora package (I'm not saying this project is doing anything nefarious, but shipping malicious code inside test data wouldn't be unprecedented).

**Comment by awakecoding** [comment]
@decathorpe we're working on adding the missing license files to help you meet your packaging requirements (SPDX declarations have always been fine so far, but we've made a script to copy the license files in each crate before publishing).

As for the test data, yes, most of them have been generated manually. Some of them were generated by quick-and-dirty PowerShell scripts that would just call ssh-keygen and putty-related tools on Windows once, just to save the time of typing hundreds of commands to get all the possible combinations of key sizes and formats.

The fact is we've just generated test files are needed to expand our test suites, and then you come along questioning their origin, as if it was something important. They're test files - why would the randomness source matter? They're used to test that we can correctly encode, decode, convert to/from various file formats.

The only file which I know we haven't generated is the Authenticode certificate chain from PSDiagnostics, because it had a weird edge case that we had to handle, and for which we wouldn't know how to generate. AFAIK, including a simple certificate chain for testing is fair use, but if you insist, we'll remove the test and the associated certificate chain at the cost of not detecting a possible regression for that edge case later.

Is that enough of an explanation for the origin of the test files? We've just generated most of them manually as needed, we didn't think it would be necessary to explain their origin, let alone document precisely *how* they've been generated so somebody else could re-generate them from scratch. How much of a proof of origin do you *really* need? If your only concern is that they could be malicious - go ahead and scan them with AVs. They're test files, not executable code.

We do want to help make the project easier to repackage by distributions, but please don't waste our time chasing ghosts. I have a hard time distinguishing what's truly necessary from what is excessive in your line of inquiry.

**Comment by decathorpe** [comment]
> @decathorpe we're working on adding the missing license files to help you meet your packaging requirements (SPDX declarations have always been fine so far, but we've made a script to copy the license files in each crate before publishing).

Thanks, this is helpful - though it looks like the picky-test-data crate was missed here:
https://github.com/Devolutions/picky-rs/tree/master/picky-test-data

> As for the test data, yes, most of them have been generated manually. Some of them were generated by quick-and-dirty PowerShell scripts that would just call ssh-keygen and putty-related tools on Windows once, just to save the time of typing hundreds of commands to get all the possible combinations of key sizes and formats.

Thank you, this was kind of the information that was missing for me. Would it make sense to add a sentence to the README to make this explicit? (Having a shell script / PowerShell script to actually reproduce the test files would be even better.)

> The fact is we've just generated test files are needed to expand our test suites, and then you come along questioning their origin, as if it was something important. They're test files - why would the randomness source matter? They're used to test that we can correctly encode, decode, convert to/from various file formats.

The source of randomness doesn't matter - I shouldn't have mentioned it, it was just an example.

> The only file which I know we haven't generated is the Authenticode certificate chain from PSDiagnostics, because it had a weird edge case that we had to handle, and for which we wouldn't know how to generate. AFAIK, including a simple certificate chain for testing is fair use, but if you insist, we'll remove the test and the associated certificate chain at the cost of not detecting a possible regression for that edge case later.

I think this is fine (though I'm not a lawyer), so I don't insist on anything ...

> Is that enough of an explanation for the origin of the test files? We've just generated most of them manually as needed, we didn't think it would be necessary to explain their origin, let alone document precisely _how_ they've been generated so somebody else could re-generate them from scratch. How much of a proof of origin do you _really_ need? If your only concern is that they could be malicious - go ahead and scan them with AVs. They're test files, not executable code.
> 
> We do want to help make the project easier to repackage by distributions, but please don't waste our time chasing ghosts. I have a hard time distinguishing what's truly necessary from what is excessive in your line of inquiry.

I do find it a little bit strange that you didn't document how the files were generated, if only if you ever wanted to re-run or modify the steps in the future, but that's beside the point.

I'm sorry that you feel like I'm wasting your time, this is definitely not my intention. Distribution packagers are usually just wary of projects that ship binary data that isn't clear what it contains and / or how it was generated. We don't want openssh backdoors getting shipped via test data, after all 😅 (again, I'm not suggesting that anything nefarious is happening here - just that this kind of test input file has been used as a payload for an attack before).

And to be completely honest, the information we get from Red Hat lawyers isn't always very clear (probably by design - lawyers being lawyers and all ...). I just try to communicate our "legal" needs as well as I can, given that I often don't necessarily know what to do to placate the lawyers, either.

In this case, knowing that the test data is just generated on-demand by yourself is hopefully all that we need to know. The Authenticode certificate chain thing sounds acceptable too. So thank you for the clarifications.

**Comment by CBenoit** [comment]
It’s now challenging to precisely track how these commands were used since the original scripts are lost, and recreating them from scratch wouldn’t be the best use of our time. Instead, I’ll paraphrase @awakecoding’s explanation in the README.md, as it should be sufficient for your needs. I understand this may cause confusion for package maintainers, and I’ll ensure more thorough documentation in the future. It’s generally easier to include this kind of information in the same PR that implements the tests, and we’ll make an effort to do so going forward. I'm improved our process for publishing the Rust crates, and I'll likely get to picky this week. I'll let you know once the new version for this crate is published.
