### ISSUE TITLE
Subject functions, types and enum fields use "organisation" instead of "organization"

### ISSUE THREAD

**Issue by Albibek** [Devolutions/picky-rs#45]
Hello.

Not trying to start any linguistical discussion here, but [RFC](https://tools.ietf.org/html/rfc5280#section-4.1.2.4) uses the "organization" spelling - with "z", not "s".

It probably could be better to use the "z"-spelling for the sake of being closer to standard writing and for people working with the certificates, which are also more familiar with the "z"-spelled names.

**Comment by awakecoding** [comment]
We're not specifically attached to one spelling or the other, in this case I think it was simply because it matched the French spelling. However, I am personally more used to the American English spelling with a 'z' and agree we should use of the same spelling found in the RFC for the sake of consistency. @bcortier-devolutions

**Comment by bcortier-devolutions** [comment]
Hi @Albibek ,
I agree to change to "organization". Generally, I prefer mirroring RFCs as much as possible as long as it respect Rust naming conventions. I see you intend to send us PR, don't hesitate to change this now because we're in the process of publishing a new breaking release of picky! :slightly_smiling_face:

**Comment by bcortier-devolutions** [comment]
Addressed by #46
