### ISSUE TITLE
RSA parts may be generated as negative

### ISSUE THREAD

**Issue by Albibek** [Devolutions/picky-rs#53]
Hi.

I've tried to parse some certificate generated using picky from golang x509 module and got the following error:
```
x509: RSA modulus is not a positive number
```

Both `openssl rsa -check` and `openssl x509` were silent about this, but here is what I have found:

http://blog.alex.org.uk/2015/10/13/rsa-modulus-is-not-a-positive-number-say-what/

My key generation code was copy-pasted from [here](https://github.com/Devolutions/picky-rs/blob/857113a52611fcf194226950a10f9d9ee5d47f29/picky/src/key.rs#L165) (I wanted my own key generation)

I've tried using `IntegerAsn1::from_unsigned_bytes_be` instead of  `IntegerAsn1::from_unsigned_bytes_be` and it worked without any additional issues. I think since BigUint is used while generating a key, it is ok to use the unsigned variant, but I did not deep too dive to be sure about it.

The go code for checking the certificates can be found [here](https://play.golang.org/p/1BedVgNIDrT)

By the way, the fucntion names are probably a bit misleading. One may think it expects signed/unsigned bytes as input since it says "from signed bytes", but still requires Vec<u8>. Maybe functions could be better understood if called like `from_bytes_be_unsigned` (more "rusty" variant) or `unsigned_from_bytes_be` (more related to Integer itself).

**Comment by CBenoit** [comment]
Wow, you're right. Current code looks wrong: `BigUint` is obviously returning the "unsigned" binary representation and is loaded as signed in our `IntegerAsn1`.
This is correctly done at this place: https://github.com/Devolutions/picky-rs/blob/master/picky/src/key.rs#L83
I'm surprised that `openssl rsa -check` and `openssl x509` are silent about this; also we never had any issue up until today and your golang test… Thank you for this valuable feedback.

Regarding naming it's actually inspired by `num_bigint_dig`: https://docs.rs/num-bigint-dig/0.6.0/num_bigint_dig/struct.BigInt.html#method.from_signed_bytes_be
Natural languages being ambiguous it's always hard to get naming right haha.
If we were to change I would personally prefer `from_bytes_be_unsigned` and `from_bytes_be_signed`.
I'm not sure about what is the best move here so I would like to gather other opinions first.
What do you think about that @awakecoding ?
I would like also hear your opinion @hug-dev since I believe you're using this in your codebase for `parsec`.
(By the way I had a look at your usage of picky in `parsec` since you're not really using `picky` crate itself you guys are unaffected by this)

**Comment by awakecoding** [comment]
Another way to call the function would be "from_unsigned_bytes_be" and "from_signed_bytes_le", as long as it says both signed/unsigned and be/le it is fine with me.

**Comment by CBenoit** [comment]
> Another way to call the function would be "from_unsigned_bytes_be" and "from_signed_bytes_le", as long as it says both signed/unsigned and be/le it is fine with me.

This is the current naming that @Albibek reported as a bit misleading.

**Comment by hug-dev** [comment]
I remember we had several headaches about this 😆 I believe #12 was about that in parts. We could not understand why it was sometimes not working (when working with TPM and HSM). We added this comment in our code at some point:

```
// To produce a valid ASN.1 RSAPublicKey structure, 0x00 is put in front of the positive
// modulus if highest significant bit is one, to differentiate it from a negative number.
modulus: IntegerAsn1::from_unsigned_bytes_be(pub_key_data),
```

The names of the methods are fine with us. As we use them in several locations, we would have to rename them with the new name but we are not against that if you can find something better 😃

**Comment by Albibek** [comment]
So, what's the plan? Want me to make a PR? Should I do only the fix or functions rename as well?

**Comment by bcortier-devolutions** [comment]
Sorry for the delay, I was on vacation.

> So, what's the plan? Want me to make a PR? Should I do only the fix or functions rename as well?

I'll take time to do that real quick!

**Comment by bcortier-devolutions** [comment]
Fix is merged and crates are updated on crates.io!
`picky-asn1 0.3.0`  has the new names for IntegerAsn1 methods.
