### ISSUE TITLE
Please include license files in the crates

### ISSUE THREAD

**Issue by nullr0ute** [Devolutions/picky-rs#56]
please include the license files in the picky-asn1, picky-asn1-der, picky-asn1-x509 crates.

**Comment by nullr0ute** [comment]
And also picky itself

**Comment by bcortier-devolutions** [comment]
Hi!
I just want to confirm what is your need. For each crate, license is [specified in the `Cargo.toml` manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) (a license is a requirement for any published crate on crates.io). See [picky Cargo.toml](https://github.com/Devolutions/picky-rs/blob/master/picky/Cargo.toml#L13) for instance.
This is similar to [tokio](https://github.com/tokio-rs/tokio).
So I believe there is no issue in how we licensed our crates.
Is there something I'm missing? Are you using a third party tool expecting to find a `LICENSE` file?
Thank you.

**Comment by awakecoding** [comment]
@nullr0ute the license is specified in each crate cargo.toml file, and the root of this git repository contains both license files. Is there something we missed in terms of proper license declaration for the project? making a copy of the license files in each subdirectories looks a bit overkill.

**Comment by nullr0ute** [comment]
Each of the actual .crate files should include the license text (the actual files) the same as is in the git repo so that they're distributed with the code.

**Comment by awakecoding** [comment]
do you know if this can be done without having a full copy of the license text files in each crate for this repo? do you have a reference on other projects that use the same license for many smaller crates, all within the same repo? I'd like to fix it

**Comment by bcortier-devolutions** [comment]
I'm not against copying each license file to each sub folder, but this definitely not a requirement for proper licensing with cargo as long as the `license` field contains a license identifier value registered in the [Linux Foundation’s Software Package Data Exchange (SPDX)](https://spdx.org/licenses/). This is checked by cargo at publish time.
Reference:
- [cargo doc](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields)
- [the book](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#adding-metadata-to-a-new-crate)

This becomes a requirement if one wants to use a license that doesn’t appear in the SPDX. In such case it is required to place the text of that license in a file, include the file in the project, and then use `license-file` field in Cargo.toml to specify the name of that file.

**Comment by nullr0ute** [comment]
> do you know if this can be done without having a full copy of the license text files in each crate for this repo? do you have a reference on other projects that use the same license for many smaller crates, all within the same repo? I'd like to fix it

One I know has done this: https://github.com/iqlusioninc/crates/pull/502 I don't know how to reference the one in the root.

**Comment by awakecoding** [comment]
@nullr0ute sorry for the late follow up on this. I checked the pull request you mentioned as reference, and they have literally copied the entire license files in each crate individually. @bcortier-devolutions pointed to the Rust docs regarding license declaration: https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#adding-metadata-to-a-new-crate

Here is the relevant part:

**For the license field, you need to give a license identifier value. The Linux Foundation’s Software Package Data Exchange (SPDX) lists the identifiers you can use for this value**. For example, to specify that you’ve licensed your crate using the MIT License, add the MIT identifier. **If you want to use a license that doesn’t appear in the SPDX, you need to place the text of that license in a file**, include the file in your project, and then use license-file to specify the name of that file instead of using the license key.

In other words, as long as the project is licensed using SPDX identifiers for known, standard license texts, you don't need to include the actual license text. It's actually better that way, because if you declare a standard license, you don't want to make sure that multiple license text files for what should be the same license, are actually identical files. If it's Apache 2.0, it's Apache 2.0, period, no room for error.

This being said, we do include the license text files once for the entire github repository, covering all the crates it contains. By the way, if you need the actual license text for SPDX identifiers, there are a couple of tools you can use in Rust for that, like licensor: https://crates.io/crates/licensor

I will close this issue for now, as we are correctly declaring the license for all of our crates, in addition to including the license text files once for the github repository, something which is actually not a hard requirement for crates.io publishing because we use standard SPDX identifiers. However, it is common to include the license texts in each github repository, so we just follow this common practice.
